runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  login: required
  script: src.main.app
- url: /img/.*
  script: src.main.app
# loans
- url: /loans
  login: required
  script: src.main.app
- url: /loans/send_reminder
  login: admin
  script: src.main.app
- url: /loans/validate/.*
  login: required
  script: src.main.app
# static files
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon\.ico

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^data$
- data
