runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: src.main.app
# loans
- url: /loans
  script: src.main.app
- url: /loans/validate/.*
  script: src.main.app
# admin frontend
- url: /admin
  script: src.main.app
  login: admin
# static files
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon\.ico

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^data$
